runtime: python39

env_variables:
  GROQ_API_KEY: "your-groq-api-key"
  REDIS_URL: "redis://localhost:6379"
  DATABASE_URL: "postgresql://user:password@localhost:5432/lead_scoring"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
